name: restaurant_task
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.7.1
  flutter_bloc: ^8.1.3
  freezed: ^2.4.1
  dartz: ^0.10.1
  dio: ^5.3.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  hive: ^2.2.3
  flutter_secure_storage: ^8.0.0
  google_fonts: ^5.1.0
  freezed_annotation: ^2.4.1
  path_provider: ^2.0.15
  hive_generator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:
  auto_route_generator:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
